'use strict';

// Generated by `docgov init`, then customized by hand — see "Documentation
// ownership" in AGENTS.md for the policy this file enforces mechanically.
//
// This config declares DATA, never logic. If you need a check that doesn't
// exist, it belongs in the engine (licorsy/docs-governance), not here —
// otherwise the engine ends up forked-by-config and duplication sneaks back
// in through the side door.

// Every rule accepts a `why` field, printed when it fails. Fill it with the
// REAL defect that motivated the rule. A rule with no real defect shouldn't
// exist.

module.exports = {
  engine: '^1',

  rules: {
    frontmatter: {
      // agents/ and commands/ use Claude Code plugin frontmatter (name,
      // description, tools, model for agents; description-only for
      // commands), not docs-governance's title/doc_type/status/version
      // schema. `description` is the one field both file kinds share and
      // the one Claude Code actually needs to route to them correctly.
      //
      // AGENTS.md and CLAUDE.md both carry the full org schema (title, doc_type,
      // description, status, version, created, updated, language) under the
      // org-wide decision that every tracked Markdown file is enumerable.
      // Only `description` is ENFORCED here, because this rule applies one
      // `required` list to everything in scope and the manifests above
      // cannot satisfy the other seven. The remaining fields are carried by
      // convention, not by check — enforcing both schemas needs two rules.
      //
      // README.md stays out: it is the rendered repository landing page, and
      // GitHub renders frontmatter there as a visible table.
      scope_dirs: ['agents', 'commands'],
      root_files: ['AGENTS.md', 'CLAUDE.md'],
      exclude_prefixes: [],
      // ids from these count toward resolving `related:`, but the files
      // themselves aren't checked
      id_only_sources: [],
      required: ['description'],
      status_enum: ['draft', 'active', 'deprecated', 'archived'],
      doc_type_enum: null, // null = don't enforce the enum
      date_fields: ['created', 'updated'],
      why: 'a missing description breaks Claude Code\'s ability to route to this agent/command at all',
    },

    'internal-links': {
      // prunes by directory NAME, at any depth
      exclude_dir_names: ['.git', 'node_modules', '.vscode', 'local-notes'],
      // links that should never be checked (e.g. gitignored target)
      skip_link_patterns: [],
    },

    'changelog-retention': {
      scope_dirs: ['agents', 'commands'],
      root_files: ['README.md', 'AGENTS.md', 'CLAUDE.md'],
      exclude_prefixes: [],
      exclude_files: [],
      marker: 'Changelog:',
      max_entries: 3,
      why: null,
    },

    'version-bump': {
      enabled: true,
    },

    // ---- Phase 2: content rules ----
    // These three facts pin the exact defects that already drifted more than
    // once in this repo's own history (see "Documentation ownership" in
    // AGENTS.md) — the 6-prefix branch taxonomy, the docs-governance CI
    // step's 3-clause guard condition, and the per-branch merge methods.
    facts: {
      // Out of shadow mode: precision is proven. These entries have caught the
      // same class of drift repeatedly with no false positive, and a pin that
      // only reports is decoration — the drift it was added for happens anyway.
      // This also makes the rule run under `--changed`, so pre-commit catches
      // it rather than CI at promotion time.
      shadow: false,
      scope_dirs: ['agents', 'commands'],
      entries: [
        {
          id: 'branch-prefix-taxonomy',
          value: 'feat, fix, refactor, docs, chore, hotfix',
          why: 'refactor/ was added to the taxonomy after feature/*->feat/* '
            + 'was renamed, and AGENTS.md/README.md briefly still said '
            + '"feature/*" — this fact caught the same class of drift twice',
          // README.md only carries this list inside the branch-flow diagram
          // itself, which fragment_sync already pins against AGENTS.md — no
          // separate prose restatement there to check.
          required_in: [
            { file: 'AGENTS.md', pattern: /`feat`,\s*`fix`,\s*`refactor`,\s*`docs`,\s*`chore`,\s*`hotfix`/ },
            { file: 'commands/create-feature.md', pattern: /`feat`,\s*`fix`,\s*`refactor`,\s*`docs`,\s*`chore`,\s*`hotfix`/ },
            {
              file: 'agents/git-governance-advisor.md',
              pattern: /`feat\/<id>-<description>`[\s\S]*`fix\/<id>-<description>`[\s\S]*`refactor\/<id>-<description>`[\s\S]*`docs\/<id>-<description>`[\s\S]*`chore\/<id>-<description>`[\s\S]*`hotfix\/<id>-<description>`/,
            },
          ],
          // the pre-refactor five-prefix list, as it would read on one line
          // if someone reverted the taxonomy edit without noticing the gap
          forbidden: [/`feat`, `fix`, `docs`, `chore`, `hotfix`(?!.*refactor)/],
        },
        {
          id: 'docs-governance-guard-clauses',
          value: "github.event_name == 'pull_request' && hashFiles('.docgov.config.js') != '' && hashFiles('.github/workflows/docs-governance.yml') == ''",
          why: 'the CI guard\'s three clauses were hardened once already '
            + '(pull_request event-name and the self-disable clause were '
            + 'both added after the fact) — restated in prose in two files '
            + 'plus the live YAML condition itself, easy for one to drift',
          required_in: [
            {
              file: 'AGENTS.md',
              pattern: /all three of[\s\S]*?hashFiles\('\.github\/workflows\/docs-governance\.yml'\) == ''/,
            },
            { file: 'README.md', pattern: /`\.github\/workflows\/docs-governance\.yml`/ },
            {
              file: '.github/workflows/pr-checks.yml',
              pattern: /github\.event_name == 'pull_request' &&[\s\S]*?hashFiles\('\.docgov\.config\.js'\) != '' &&[\s\S]*?hashFiles\('\.github\/workflows\/docs-governance\.yml'\) == ''/,
            },
          ],
        },
        {
          id: 'merge-method-policy',
          value: 'develop: merge, squash | staging, main: merge only',
          why: 'the policy an operator reads and the allowed_merge_methods the '
            + 'script actually PUTs are four files apart; the whole point of '
            + 'restricting promotions to merge commits is lost the moment one '
            + 'of them quietly says otherwise',
          required_in: [
            // Cells anchored on their closing `|` on purpose: unanchored, the
            // pattern matches "merge commit, squash, rebase" as a prefix and
            // passes. Found by deliberately breaking the equivalent pin in
            // licorsy/.github rather than by trusting it.
            {
              file: 'AGENTS.md',
              pattern: /`develop`\s*\|\s*merge commit, squash\s*\|[\s\S]*?`staging`, `main`\s*\|\s*merge commit only\s*\|/,
            },
            {
              file: 'README.md',
              pattern: /`develop` takes merge or squash, `staging` and `main` take merge commits\s+only/,
            },
            {
              file: 'scripts/setup-branch-protection.sh',
              // [ \t] rather than \s around the newlines: \s matches \n too, so
              // `\s*\n\s*` is ambiguous and backtracks. Same match, linear.
              pattern: /if \[ "\$BRANCH" = "develop" \]; then[ \t]*\n[ \t]*MERGE_METHODS='\["merge", "squash"\]'[ \t]*\n[ \t]*else[ \t]*\n[ \t]*MERGE_METHODS='\["merge"\]'/,
            },
            {
              file: 'agents/git-governance-advisor.md',
              pattern: /`staging` and `main` accept merge commits only; `develop` also accepts squash/,
            },
          ],
        },
        {
          id: 'commit-msg-lint-skips-merges',
          value: 'git log --no-merges --format=%s',
          why: 'this repo has had the flag since the defect was first hit here, '
            + 'but never pinned it — so every pr-checks.yml scaffolded from an '
            + 'earlier revision carried the broken form, and three sibling repos '
            + 'reproduced a check that fails by construction on every promotion '
            + 'PR. The flag being correct here is exactly why nobody noticed. '
            + 'This is the copy that matters most: it is the one others are made '
            + 'from',
          required_in: [
            {
              file: '.github/workflows/pr-checks.yml',
              pattern: /git log --no-merges --format=%s/,
            },
          ],
        },
      ],
    },
    // sum_decomposition: { entries: [
    //   { file: 'docs/index.md', pattern: /(\d+) \+ (\d+) \+ (\d+) = (\d+)/ },
    // ] },
    // version_citations: { scope_dirs: ['agents', 'commands'], root_files: ['README.md', 'CLAUDE.md'] },

    // ---- Phase 3: covers: in the destination's frontmatter vs. the source's version: ----
    // sync_destinations: {
    //   targets: ['docs/prompts/006-project.md'],
    //   scope_dirs: ['agents', 'commands'], root_files: ['README.md', 'AGENTS.md', 'CLAUDE.md'],
    // },

    // ---- Phase 4: fragment/citation/numbered-reference rules promoted from
    // repeated layer-4 (LLM-audit) findings — see docs-governance README's
    // "The ratchet" ----
    // The branch-flow diagram is declared once, in AGENTS.md (see
    // "Documentation ownership" above), and must exact-byte-match the copy
    // in README.md — both are marked with the same
    // <!-- fragment:branch-flow:start/end --> pair, wrapping the fenced
    // diagram (the markers sit outside the fence, not inside it).
    fragment_sync: {
      fragments: [
        { id: 'branch-flow', source: 'AGENTS.md', destinations: ['README.md'] },
      ],
    },
  },
};
